http:
  routers:
    api:
      rule: Host(`traefik.beta.math.wmflabs.org`)
      service: api@internal
      middlewares:
        - auth
      entryPoints:
        - websecure
      tls:
        certResolver: le
    api-proxy:
      rule: PathPrefix(`/`)
      service: api@internal
      middlewares:
        - auth
      entryPoints:
        - dashboard
    whoami-80:
      rule: HostRegexp(`{host:.+}`)
      service: whoami-beta@docker
      middlewares:
        - redirect
      entryPoints:
        - web
      priority: 100
    whoami-443:
      rule: Host(`whoami.beta.math.wmflabs.org`)
      service: whoami-beta@docker
      entryPoints:
       - websecure
      tls:
        certResolver: le
{{$services := list "mathoid" "whoami"}}
{{range $s := $services}}
    whoami{{$s}}:
      rule: Host(`service-{{$s}}.beta.math.wmflabs.org`)
      service: {{$s}}-beta@docker
      entryPoints:
       - websecure
      tls:
        certResolver: le
{{end}}
    home:
      rule: Host(`home.beta.math.wmflabs.org`)
      service: whoami-beta@docker
      entryPoints: [websecure]
      tls:
        certResolver: le
      middlewares:
        - test-redirectregex
  middlewares:
    auth:
      basicAuth:
        usersFile: /run/secrets/traefik_users
    redirect:
      redirectScheme:
        scheme: https
    test-redirectregex:
      redirectRegex:
        regex: "^https://home.beta.math.wmflabs.org/(.*)"
        replacement: "https://wikitech.wikimedia.org/wiki/Nova_Resource:Math"
