version: '3.4'

services:
  reverse-proxy:
    image: traefik
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik-conf:/traefik-conf:ro
    labels:
      - "traefik.enable=false"
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
  mathoid:
    container_name: mathoid
    image: docker-registry.wikimedia.org/repos/mediawiki/services/mathoid:latest
    restart: always
    labels:
      - traefik.http.routers.mathoid-beta.rule=Host(`mathoid.beta.math.wmflabs.org`)
      - traefik.http.services.mathoid-beta.loadbalancer.server.port=10044
      - traefik.http.routers.mathoid-beta.tls=true
      - traefik.http.routers.mathoid-beta.tls.certresolver=le
  database:
    container_name: db
    image: mariadb:11.6
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - mw-database:/var/lib/mysql
      - ./dumps:/docker-entrypoint-initdb.d
      - /data/project/backup:/backup:ro
    secrets:
      - db_root_password
    labels:
      - "traefik.enable=false"
  mediawiki:
    image: ghcr.io/mardi4nfdi/apache-assets-production:latest
    restart: always
    container_name: mw
    ports:
      - 8080:80
    volumes:
      - mw-images:/var/www/html/w/images
      - mw-cache:/cache
      - ./LocalSettings.php:/shared/LocalSettings.php:ro
      - ./LocalSettings.php:/var/www/html/w/LocalSettings.php:ro
      - ./LocalSettings.d:/shared/LocalSettings.d:ro
      - ./LocalSettings.d:/var/www/html/w/LocalSettings.d:ro
    environment:
      WIKIBASE_HOST: mediawiki-fpm
  mediawiki-fpm:
    image: ghcr.io/mardi4nfdi/wikibase-production:latest
    container_name: mediawiki-fpm
    restart: unless-stopped
    volumes:
      - mw-images:/var/www/html/w/images
      - mw-cache:/cache
      - ./LocalSettings.php:/shared/LocalSettings.php:ro
      - ./LocalSettings.php:/var/www/html/w/LocalSettings.php:ro
      - ./LocalSettings.d:/shared/LocalSettings.d:ro
      - ./LocalSettings.d:/var/www/html/w/LocalSettings.d:ro
      - /data/project/wdump/math-qid:/var/www/html/math-qid:ro
      - ./container-scripts/mw:/var/www/html/scripts:ro
secrets:
   db_root_password:
     file: secret/db_root_password.txt
volumes:
  mw-images:
  mw-database:
  mw-cache:
