version: '3.4'

services:
  reverse-proxy:
    image: traefik
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      # The Web UI (enabled by --api.insecure=true)
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik-conf:/traefik-conf:ro
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
  mathoid:
    container_name: mathoid
    image: physikerwelt/mathoid:latest
    ports:
      - 10042:10042
    restart: always
    labels:
      - traefik.http.routers.mathoid.rule=Host(`mathoid.beta.math.wmflabs.org`)
      - traefik.http.routers.mathoid.tls=true
      - traefik.http.routers.mathoid.tls.certresolver=le
  database:
    container_name: db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - mw-database:/var/lib/mysql
      - ./dumps:/docker-entrypoint-initdb.d
    secrets:
      - db_root_password
    labels:
      - "traefik.enable=false"
secrets:
   db_root_password:
     file: secret/db_root_password.txt
volumes:
  mw-images:
  mw-database: