log:
  level: DEBUG
accessLog: {}
api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker: {}
  file:
    directory: "/traefik-conf"
    watch: true

certificatesResolvers:
  le:
    acme:
      tlschallenge: true
      storage: /letsencrypt/acme.json
      email: wiki@physikerwelt.de
      httpChallenge:
        # used during the challenge
        entryPoint: web

