#!/bin/sh

echo "Script called with $1"

exit 0

# Hide the current LocalSettings.php if it exists
if [ -f /var/www/html/LocalSettings.php ]
then
    mv /var/www/html/LocalSettings.php /var/www/html/LocalSettings.php.docker.tmp
fi

# Install the base html tables on the db server & remove the generated LocalSettings.php
php maintenance/install.php --dbname=wiki_$1 --dbserver="db" --dbuser=wiki --dbpass=***REMOVED*** --server="https://$1.beta.physikerwelt.de/" --lang=$1 --pass=***REMOVED*** "Wiki $1" "admin"
rm /var/www/html/LocalSettings.php

# Move back the old LocalSettings if we had moved one!
if [ -f /var/www/html/LocalSettings.php.docker.tmp ]
then
    mv /var/www/html/LocalSettings.php.docker.tmp /var/www/html/LocalSettings.php
fi
export SERVER_NAME=$1.beta.physikerwelt.de
echo "Updating $SERVER_NAME"
php /var/www/html/maintenance/update.php --quick
bzcat math-qid/$1.xml.bz2 | php /var/www/html/maintenance/importDump.php
php /var/www/html/maintenance/initSiteStats.php
